name: The_dope_plugin
version: '${version}'
main: com.lukcoding.the_dope_plugin.The_dope_plugin
api-version: 1.18
authors: [ LukCoding ]
description: Amazing plugin I use in my server
commands:
  kit:
    description: Give a person a start to building
    usage: /kit
 
